//Auto-generated by serialize3.exe
//Defines type ids for classes serializable via a pointer (Note: could be directly added to injected file)
#pragma once

const TTypeId xtd__TMyClass_TYPE_ID = 1;
const TTypeId xtd__TMyClass1_TYPE_ID = 2;
